[colors]
[colors.primary]
background = "#232829"
foreground = "#d6dcda"

[colors.normal]
black   = "#232829"
red     = "#a78181"
green   = "#8aad8a"
yellow  = "#b3b393"
blue    = "#9eaeb8"
magenta = "#c0a5c0"
cyan    = "#adc0c7"
white   = "#d6dcda"

[colors.bright]
black   = "#788387"
red     = "#ceb6b6"
green   = "#bdd3bd"
yellow  = "#d5d5c1"
blue    = "#c6d0d6"
magenta = "#dac8da"
cyan    = "#cbd8dd"
white   = "#d6dcd9"

[colors.cursor]
text   = "#232829"
cursor = "#d6dcda"
