# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#232829"

# Main text color
theme[main_fg]="#d6dcda"

# Title color for boxes
theme[title]="#c0a5c0"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#adc0c7"

# Background color of selected item in processes box
theme[selected_bg]="#788387"

# Foreground color of selected item in processes box
theme[selected_fg]="#d6dcda"

# Color of inactive/disabled text
theme[inactive_fg]="#788387"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c0a5c0"

# Box outline and divider line color
theme[cpu_box]="#8aad8a"
theme[mem_box]="#8aad8a"
theme[net_box]="#8aad8a"
theme[proc_box]="#8aad8a"
theme[div_line]="#788387"

# Gradient for all meters and graphs
theme[temp_start]="#adc0c7"
theme[temp_mid]="#9eaeb8"
theme[temp_end]="#8aad8a"


theme[cpu_start]="#adc0c7"
theme[cpu_mid]="#9eaeb8"
theme[cpu_end]="#8aad8a"


theme[free_start]="#9eaeb8"
theme[free_mid]="#b3b393"
theme[free_end]="#b3b393"


theme[cached_start]="#b3b393"
theme[cached_mid]="#b3b393"
theme[cached_end]="#b3b393"


theme[available_start]="#adc0c7"
theme[available_mid]="#adc0c7"
theme[available_end]="#adc0c7"


theme[used_start]="#8aad8a"
theme[used_mid]="#8aad8a"
theme[used_end]="#8aad8a"


theme[download_start]="#b3b393"
theme[download_mid]="#adc0c7"
theme[download_end]="#9eaeb8"


theme[upload_start]="#b3b393"
theme[upload_mid]="#adc0c7"
theme[upload_end]="#9eaeb8"