# Background and foreground colors
background = #232829
foreground = #d6dcda

# Standard colors
palette = 0=#232829
palette = 1=#a78181
palette = 2=#8aad8a
palette = 3=#b3b393
palette = 4=#9eaeb8
palette = 5=#c0a5c0
palette = 6=#adc0c7
palette = 7=#d6dcda

# Bright colors
palette = 8=#788387
palette = 9=#ceb6b6
palette = 10=#bdd3bd
palette = 11=#d5d5c1
palette = 12=#c6d0d6
palette = 13=#dac8da
palette = 14=#cbd8dd
palette = 15=#d6dcd9
