background            #232829
foreground            #d6dcda

# black
color0  #232829
color8  #788387

# red
color1  #a78181
color9  #ceb6b6

# green
color2  #8aad8a
color10 #bdd3bd

# yellow
color3  #b3b393
color11 #d5d5c1

# blue
color4  #9eaeb8
color12 #c6d0d6

# magenta
color5  #c0a5c0
color13 #dac8da

#cyan
color6  #adc0c7
color14 #cbd8dd

#white
color7  #d6dcda
color15 #d6dcd9


