exec-once = uwsm-app -- hypridle
exec-once = aether --apply-blueprint joooww
exec-once = uwsm-app -- /bin/sh -c "while true; do waybar 2>&1 | logger -t waybar; done"
exec-once = uwsm-app -- nm-applet
exec-once = uwsm-app -- blueman-tray
exec-once = uwsm-app -- fcitx5
exec-once = uwsm-app -- swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
