source = ~/.config/current-theme/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba(41, 35, 35, 1)
    path = ~/.config/current-theme/background
    blur_passes = 3
    noise = 0.01
    contrast = 0.9
    brightness = 0.8
    vibrancy = 0.2
}

animations {
    enabled = true
}

input-field {
    monitor =
    size = 250, 60
    position = 0, -200
    halign = center
    valign = center
    inner_color = rgba(41, 35, 35, 0.66)
    outer_color = rgba(169, 112, 169, 1)
    outline_thickness = 4
    font_family = JetBrainsMono Nerd Font
    font_color = rgba(220, 214, 214, 1)
    placeholder_text = Unlock
    check_color = rgba(112, 169, 169, 1)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    rounding = 12
    shadow_passes = 3
    fade_on_empty = false
}

label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    font_size = 80
    inner_color = rgba(41, 35, 35, 0.66)
    outer_color = rgba(169, 112, 169, 1)
    outline_thickness = 4
    font_family = JetBrainsMono Nerd Font
    font_color = rgba(220, 214, 214, 1)
    position = 0, 60
    halign = center
    valign = center
}

auth {
    fingerprint:enabled = true
}
