-- Hyprland config

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/envs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("envs")
-- Source: ~/.config/hypr/looknfeel.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("looknfeel")
-- Source: ~/.config/hypr/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")
-- Source: ~/.config/hypr/windows.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("windows")

-- Theme colors (from active theme)
-- Source: ~/.config/current-theme/theme/hyprland.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland")

-- User overrides
-- Source: ~/.config/hypr/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors")
-- Source: ~/.config/hypr/bindings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("bindings")
-- Source: ~/.config/hypr/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostart")
