-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/current-theme/theme/hyprlock.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprlock")

-- TODO: manual review — unknown section 'background {' on line 7

-- TODO: manual review — unknown section 'input-field {' on line 22

-- TODO: manual review — unknown section 'label {' on line 41

-- TODO: manual review — unknown section 'auth {' on line 55
hl.config({
    general = {
        ignore_empty_input = true,
    },
    animations = {
        enabled = true,
    },
})

