-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 8

-- TODO: manual review — unknown section 'listener {' on line 13

-- TODO: manual review — unknown section 'listener {' on line 18
hl.config({
    general = {
        lock_cmd = "hyprlock",
        before_sleep_cmd = "loginctl lock-session",
        after_sleep_cmd = "hyprctl dispatch dpms on",
        inhibit_sleep = 10,
    },
})

