input {
    kb_layout = us,de,hu
    kb_variant =
    kb_model =
    kb_options = compose:caps,grp:alts_toggle
    kb_rules =
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = false
    }
}
