-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
    opacity = "0.97 0.9",
})

hl.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    -- TODO: manual review — unmapped window rule action: "no_focus on"
})

hl.window_rule({
    match = {
        class = "^(1[p|P]assword)$",
    },
    -- TODO: manual review — unmapped window rule action: "no_screen_share on"
    tag = "+floating-window",
})

hl.window_rule({
    match = {
        class = "^(Bitwarden)$",
    },
    -- TODO: manual review — unmapped window rule action: "no_screen_share on"
    tag = "+floating-window",
})

hl.window_rule({
    match = {
        class = "((google-)?[cC]hrom(e|ium)|[bB]rave-browser|[mM]icrosoft-edge|Vivaldi-stable|helium)",
    },
    tag = "+chromium-based-browser",
})

hl.window_rule({
    match = {
        class = "([fF]irefox|zen|librewolf)",
    },
    tag = "+firefox-based-browser",
})

hl.window_rule({
    match = {
        tag = "chromium-based-browser",
    },
    -- TODO: manual review — unmapped window rule action: "tile on"
    opacity = "1 0.97",
})

hl.window_rule({
    match = {
        tag = "firefox-based-browser",
    },
    opacity = "1 0.97",
})

hl.window_rule({
    match = {
        initial_title = "((?i)(?:[a-z0-9-]+\\.)*youtube\\.com_/|app\\.zoom\\.us_/wc/home)",
    },
    opacity = "1.0 1.0",
})

hl.window_rule({
    match = {
        class = ".*[Rr]esolve.*",
        float = 1,
    },
    -- TODO: manual review — unmapped window rule action: "stay_focused on"
})

hl.layer_rule({
    match = { namespace = "match:namespace selection" },
    -- TODO: manual review — unmapped layer rule: "no_anim on"
})

hl.window_rule({
    match = {
        class = "^(jetbrains-.*)$",
        title = "^(splash)$",
        float = 1,
    },
    tag = "+jetbrains-splash",
})

hl.window_rule({
    match = {
        tag = "jetbrains-splash",
    },
    center = true,
    -- TODO: manual review — unmapped window rule action: "no_focus on"
    -- TODO: manual review — unmapped window rule action: "border_size 0"
})

hl.window_rule({
    match = {
        class = "^(jetbrains-.*)",
        title = "^()$",
        float = 1,
    },
    tag = "+jetbrains",
})

hl.window_rule({
    match = {
        tag = "jetbrains",
    },
    center = true,
    -- TODO: manual review — unmapped window rule action: "stay_focused on"
    -- TODO: manual review — unmapped window rule action: "border_size 0"
})

hl.window_rule({
    match = {
        class = "^(jetbrains-.*)",
        title = "^()$",
        float = 1,
    },
    -- TODO: manual review — unmapped window rule action: "min_size (monitor_w*0.5) (monitor_h*0.5)"
})

hl.window_rule({
    match = {
        class = "^(jetbrains-.*)$",
        title = "^(win.*)$",
        float = 1,
    },
    -- TODO: manual review — unmapped window rule action: "no_initial_focus on"
})

hl.window_rule({
    match = {
        class = "^(jetbrains-.*)$",
    },
    -- TODO: manual review — unmapped window rule action: "no_follow_mouse on"
})

hl.window_rule({
    match = {
        class = "(Share|localsend)",
    },
    float = true,
    center = true,
})

hl.window_rule({
    match = {
        title = "(Picture.?in.?[Pp]icture)",
    },
    tag = "+pip",
})

hl.window_rule({
    match = {
        tag = "pip",
    },
    float = true,
    pin = true,
    size = "600 338",
    -- TODO: manual review — unmapped window rule action: "keep_aspect_ratio on"
    -- TODO: manual review — unmapped window rule action: "border_size 0"
    opacity = "1 1",
    move = "(monitor_w-window_w-40) (monitor_h*0.04)",
})

hl.window_rule({
    match = {
        class = "qemu",
    },
    opacity = "1 1",
})

hl.window_rule({
    match = {
        class = "com.libretro.RetroArch",
    },
    fullscreen = true,
    opacity = "1 1",
    -- TODO: manual review — unmapped window rule action: "idle_inhibit fullscreen"
})

hl.window_rule({
    match = {
        class = "steam",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "steam",
        title = "Steam",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "steam",
    },
    opacity = "1 1",
})

hl.window_rule({
    match = {
        class = "steam",
        title = "Steam",
    },
    size = "1100 700",
})

hl.window_rule({
    match = {
        class = "steam",
        title = "Friends List",
    },
    size = "460 800",
})

hl.window_rule({
    match = {
        class = "steam",
    },
    -- TODO: manual review — unmapped window rule action: "idle_inhibit fullscreen"
})

hl.window_rule({
    match = {
        tag = "floating-window",
    },
    float = true,
    center = true,
    size = "875 600",
})

hl.window_rule({
    match = {
        class = "(org.gnome.NautilusPreviewer|org.gnome.Evince|com.gabm.satty|About|TUI.float|imv|mpv)",
    },
    tag = "+floating-window",
})

hl.window_rule({
    match = {
        class = "(xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus)",
        title = "^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*)",
    },
    tag = "+floating-window",
})

hl.window_rule({
    match = {
        class = "org.gnome.Calculator",
    },
    float = true,
})

--windowrule = fullscreen on, match:class org.omarchy.screensaver
--windowrule = float on, match:class org.omarchy.screensaver

hl.window_rule({
    match = {
        class = "^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$",
    },
    opacity = "1 1",
})

hl.window_rule({
    match = {
        tag = "pop",
    },
    rounding = 8,
})

hl.window_rule({
    match = {
        tag = "noidle",
    },
    -- TODO: manual review — unmapped window rule action: "idle_inhibit always"
})

hl.window_rule({
    match = {
        class = "(Alacritty|kitty|com.mitchellh.ghostty)",
    },
    tag = "+terminal",
})

hl.window_rule({
    match = {
        title = "WebcamOverlay",
    },
    float = true,
    pin = true,
    -- TODO: manual review — unmapped window rule action: "no_initial_focus on"
    -- TODO: manual review — unmapped window rule action: "no_dim on"
    move = "(monitor_w-window_w-40) (monitor_h-window_h-40)",
})

