# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#292323"

# Main text color
theme[main_fg]="#dcd6d6"

# Title color for boxes
theme[title]="#a970a9"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#70a9a9"

# Background color of selected item in processes box
theme[selected_bg]="#877878"

# Foreground color of selected item in processes box
theme[selected_fg]="#dcd6d6"

# Color of inactive/disabled text
theme[inactive_fg]="#877878"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a970a9"

# Box outline and divider line color
theme[cpu_box]="#70a970"
theme[mem_box]="#70a970"
theme[net_box]="#70a970"
theme[proc_box]="#70a970"
theme[div_line]="#877878"

# Gradient for all meters and graphs
theme[temp_start]="#70a9a9"
theme[temp_mid]="#7070a9"
theme[temp_end]="#70a970"


theme[cpu_start]="#70a9a9"
theme[cpu_mid]="#7070a9"
theme[cpu_end]="#70a970"


theme[free_start]="#7070a9"
theme[free_mid]="#a9a970"
theme[free_end]="#a9a970"


theme[cached_start]="#a9a970"
theme[cached_mid]="#a9a970"
theme[cached_end]="#a9a970"


theme[available_start]="#70a9a9"
theme[available_mid]="#70a9a9"
theme[available_end]="#70a9a9"


theme[used_start]="#70a970"
theme[used_mid]="#70a970"
theme[used_end]="#70a970"


theme[download_start]="#a9a970"
theme[download_mid]="#70a9a9"
theme[download_end]="#7070a9"


theme[upload_start]="#a9a970"
theme[upload_mid]="#70a9a9"
theme[upload_end]="#7070a9"