-- This file is not a full hyprland configuration.
-- It is intended to be included in your main hyprland.conf.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local activeBorderColor = "rgb(7070a9)"

hl.config({
    general = {
        col = {
            active_border = activeBorderColor,
        },
    },
    group = {
        col = {
            border_active = activeBorderColor,
        },
    },
})

