background            #292323
foreground            #dcd6d6

# black
color0  #292323
color8  #877878

# red
color1  #a97070
color9  #be8d8d

# green
color2  #70a970
color10 #8dbe8d

# yellow
color3  #a9a970
color11 #bebe8d

# blue
color4  #7070a9
color12 #8d8dbe

# magenta
color5  #a970a9
color13 #be8dbe

#cyan
color6  #70a9a9
color14 #8dbebe

#white
color7  #dcd6d6
color15 #dcd6d6


